services:
  - type: web
    name: logistic-balar
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_PASSWORD
        value: balar2026
      - key: NODE_VERSION
        value: 22
